---
title: "Untitled"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
library(networkD3)
library(tidyverse)
library(grDevices)
library(shiny)
library(fiftystater)

#load data
nodes <- read.csv("../data/output_data/nodes_proc.csv")
simp_edges <- read.csv("../data/output_data/simplified_edges.csv")
nodes <- nodes %>% 
  mutate(label = paste0(last_name, ", ", first_name, " (", party, "-", state, ")"))

# Plotting function
force_network_plot <- function(id){
  # Filter edges to get ones we want
  senator_edges <- simp_edges %>% 
    select(-X) %>%
    filter((from == id | to == id))
  senator_edges <- senator_edges[order(senator_edges$weight,decreasing = TRUE)[1:20],]
  # Then subset nodes
  nodes_subset <- nodes %>%
    filter((bioguideId %in% senator_edges$to | bioguideId %in% senator_edges$from))
  
  # Set target and source as indices to node data
  # minus 1 because it converts to JS which uses 0-indexing
  senator_edges <- senator_edges %>%
    mutate(source = match(from, nodes_subset$bioguideId) - 1,
           target = match(to, nodes_subset$bioguideId) - 1)
  
  p <- forceNetwork(Links = senator_edges, Nodes = nodes_subset, 
               Source = "source", Target = "target", 
               Value = "weight", NodeID = "label", Group = "party",
               # -- Nodes and labels
               fontSize = 15,
               fontFamily = "sans-serif",
               opacity = 0.6, 
               opacityNoHover = 0.5,
               # -- Edges
               arrows = TRUE,
               linkColour = c("grey", "orange"),
               # -- Layout
               linkDistance = 150,
               charge = -50,
               # -- General params
               colourScale = JS('d3.scaleOrdinal().range(["green", "blue", "red"]).domain(function(d) { (d.party); });'),
               zoom = TRUE,
               bounded = TRUE
               )
  return(p)
}
```

Column {.sidebar data-width=300}
-----------------------------------------------------------------------

### Enter Input
Choose your state:

```{r}
selectInput(inputId = "state",
            label = "Select a state", choices = state.abb,
            selectize = FALSE)
```

Column
-----------------------------------------------------------------------

### Senator A

```{r, echo = FALSE}

renderForceNetwork({
  sen_ID <- nodes %>% filter(state == input$state)
  sen_ID <- unique(as.character(sen_ID$bioguideId))
  force_network_plot(sen_ID[1])
})
```

### Senator B

```{r, echo = FALSE}

renderForceNetwork({
  sen_ID <- nodes %>% filter(state == input$state)
  sen_ID <- unique(as.character(sen_ID$bioguideId))
  force_network_plot(sen_ID[2])
})
```


