---
title: "Map"
output: 
  flexdashboard::flex_dashboard:
    layout: rows
runtime: shiny
---

```{r setup, include=FALSE}
library(highcharter)
library(tidyverse)
library(treemap)
library(flexdashboard)
library(viridisLite)

thm <- 
  hc_theme(
    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Source Sans Pro")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )

mapdata3 <- read_csv("./data/mapdata3.csv")
```

Input {.sidebar data-width=300}
-------------------------------------
### Inputs

```{r}
radioButtons(inputId = "session",
            label = "Select legislative session",
            choices = c("All"="",
                        "113th Session" = "113",
                        "114th Session" = "114",
                        "115th Session" = "115"),
            selected = NULL)
selectInput(inputId = "policyarea",
           label = "Select Bill Policy Area",
           choices = c("All"=".",
             "Education" = "Education",
             "Health" = "Health",
             "Public Lands and Natural Resources" = "Public Lands and Natural Resources",
             "Taxation" ="Taxation",
               "Housing and Community Development" = "Housing and Community Development",
             "Transportation and Public Works" = "Transportation and Public Works",
             "Sports and Recreation" = "Sports and Recreation",
             "Labor and Employment" = "Labor and Employment" ,
             "Commerce" = "Commerce",
             "Animals"  = "Animals",
             "Water Resources Development" = "Water Resources Development",
             "Energy" = "Energy",
             "Economics and Public Finance" = "Economics and Public Finance",
             "Government Operations and Politics" = "Government Operations and Politics" , 
             "International Affairs"   = "International Affairs"  ,
             "Armed Forces and National Security"  =   "Armed Forces and National Security", 
             "Science, Technology, Communications" = "Science, Technology, Communications",
             "Emergency Management"  = "Emergency Management" ,
             "Crime and Law Enforcement" = "Crime and Law Enforcement",
             "Finance and Financial Sector"  = "Finance and Financial Sector",
             "Foreign Trade and International Finance" = "Foreign Trade and International Finance", 
             "Agriculture and Food" = "Agriculture and Food",
             "Social Welfare" = "Social Welfare", 
             "Native Americans"  = "Native Americans",
             "Environmental Protection" ="Environmental Protection",
             "Arts, Culture, Religion"= "Arts, Culture, Religion",
             "Congress" = "Congress",
             "Immigration"  = "Immigration" ,
             "Civil Rights and Liberties, Minority Issues" = "Civil Rights and Liberties, Minority Issues",
             "Private Legislation" = "Private Legislation",
             "None reported"  = "None reported", 
             "Families" = "Families",
             "Law"  = "Law",
             "Social Sciences and History" = "Social Sciences and History",
             "Animal and plant health" = "Animal and plant health"))
```

### Policy area input

```{r}
selectInput(inputId = "state", 
            label = "Select a state", 
            choices = state.name,
            selectize = FALSE)
```


Row {data-height=400}
-------------------------------------
### Map 

```{r}
data("usgeojson")

data_map <- reactive({    
    mapdata3 %>% 
      filter(session == input$session) %>% 
      group_by(state) %>% 
      filter(policy_area == input$policyarea) %>% 
      mutate(total_submit = sum(n())) %>% 
      ungroup()  
    })

n <- 4
colstops <- data.frame(
  q = (0 : n) / n,
  c = substring(viridis(n + 1), 0, 7)) %>%
  list.parse2()

renderHighchart({
  highchart() %>%
  hc_add_series_map(map = usgeojson, data_map(), name = "Bills submitted",
                    value = "total_submit", joinBy = c("woename", "state_name"),
                    dataLabels = list(enabled = TRUE,
                                      format = '{point.properties.postalcode}')) %>%
  hc_colorAxis(stops = colstops) %>%
  hc_legend(valueDecimals = 0) %>%
  hc_mapNavigation(enabled = TRUE) %>%
  hc_add_theme(thm)
})
```

### Area

```{r}
data_areas <- reactive({    
    mapdata3 %>% 
      filter(session == input$session) %>% 
      filter(state_name == input$state) %>% 
      group_by(policy_area) %>% 
      mutate(total_submit = sum(n())) %>% 
      ungroup()  
    })

renderHighchart({
  tm <- treemap(data_areas(), "policy_area",
                vSize = "total_submit", palette = rev(viridis(6)))
  highchart() %>% 
    hc_add_series_treemap(tm, layoutAlgorithm = "squarified") %>% 
    hc_add_theme(thm)
})
```

