---
title: "SenateBEAT"
output: 
  flexdashboard::flex_dashboard:
    data-orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
library(highcharter)
library(DT)
library(networkD3)
library(d3heatmap)
library(tidyverse)
library(treemap)
library(flexdashboard)
library(viridisLite)

thm <- 
  hc_theme(
    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "white",
      style = list(fontFamily = "Source Sans Pro")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )

# Data read in/processing
nodes <- read.csv("./data/nodes_proc.csv")
simp_edges <- read.csv("./data/simplified_edges.csv")
nodes <- nodes %>% mutate(label = paste0(last_name, ", ", first_name, " (", party, "-", state, ")"))
mapdata3 <- read_csv("./data/mapdata3.csv")
subject_matrix <- nodes %>%
  select(bioguideId, label, party, in_113, in_114, in_115) %>%
  left_join(read_csv("./data/member_leg_subject_matrix.csv"))
  

policy_area_list <- mapdata3 %>% 
  arrange(policy_area) %>% 
  .$policy_area %>% 
  unique()

mapdata3 <- mapdata3 %>%
  group_by(session, state_name, state, policy_area) %>%
  summarise(total_submit = sum(n()))
```

Home
====================================
### Welcome to SenateBEAT

#### Introduction, blah blah blah 

### Another thing to look at

Wow this is cool!

### Let's see another

Nice

### Last one for now

Great


Bills Submitted {data-orientation=rows}
=====================================

Input {.sidebar}
-------------------------------------
### Inputs

```{r input_objects}
radioButtons(inputId = "session",
            label = "Select legislative session",
            choices = c("All"="*",
                        "113th Session" = "113",
                        "114th Session" = "114",
                        "115th Session" = "115"),
            selected = "*")

selectInput(inputId = "policyarea",
           label = "Select Bill Policy Area",
           choices = c("All"="*", policy_area_list))
```
<br><br>

### Policy area input

```{r}
selectInput(inputId = "state", 
            label = "Select a state", 
            choices = c("All" = "*", state.name),
            selectize = FALSE)
```


Row {data-height=600}
-------------------------------------
### Map

```{r}
data("usgeojson")

data_map <- reactive({
  mapdata3 %>%
    filter(grepl(input$session, session)) %>%
    filter(grepl(input$policyarea, policy_area)) 
  })

n <- 4
colstops <- data.frame(
  q = (0 : n) / n,
  c = substring(rev(viridis(n + 1)), 0, 7)) %>%
  list.parse2()

renderHighchart({
  dat <- data_map() %>%
    group_by(state_name) %>%
    summarise(total_submit = sum(total_submit))
  
  highchart() %>%
  hc_add_series_map(map = usgeojson, dat, name = "Bills submitted",
                    value = "total_submit", joinBy = c("woename", "state_name"),
                    dataLabels = list(enabled = TRUE,
                                      format = '{point.properties.postalcode}')) %>%
  hc_colorAxis(stops = colstops) %>%
  hc_legend(valueDecimals = 0) %>%
  hc_title(text = paste0(ifelse(input$policyarea == "*", "All", input$policyarea), " bills")) %>%
  hc_mapNavigation(enabled = TRUE) %>%
  hc_add_theme(thm)
})
```

Row {data-height=400}
-------------------------------------
### Policy Area

```{r}
data_areas <- reactive({
  # Get national totals
  national_totals <- mapdata3 %>% 
    group_by(policy_area, session) %>% 
    summarise(national_total = sum(total_submit)) %>% 
    ungroup()
  
  mapdata3 %>%
    left_join(national_totals) %>%
    filter(grepl(input$session, session)) %>%
    filter(grepl(input$state, state_name))
  })


renderHighchart({
  tm <- treemap(data_areas(), "policy_area",
                vSize = "total_submit", vColor = "national_total",
                type = "value", palette = rev(viridis(6)))
  # highchart() %>% 
  #   hc_add_series_treemap(tm, layoutAlgorithm = "squarified") %>% 
  #   hc_add_theme(thm)
  hctreemap(tm) %>%
    hc_add_theme(thm) %>%
    hc_legend(align = "center", enabled = TRUE)
})
```




Senate Overview {data-orientation=columns}
=====================================

Input {.sidebar}
-------------------------------------

```{r}
radioButtons(inputId = "session2",
            label = "Select legislative session",
            choices = c("All"="*",
                        "113th Session" = "113",
                        "114th Session" = "114",
                        "115th Session" = "115"),
            selected = NULL)

checkboxGroupInput(inputId = "party",
            label = "Select party",
            choices = c("Republican" = "R",
                        "Democratic" = "D",
                        "Independent" = "I"),
            selected = c("R", "D", "I"))

numericInput(inputId = "matrix_page",
             label = "Select heatmap page", value = 1,
             min = 1, max = 21, step = 1)
```

Column
-------------------------------------

### Heatmap 

```{r}
data_heatmap <- reactive({
  filtered <- subject_matrix %>%
    filter(party %in% input$party)

  if (input$session2 == "113") {
    filtered <- filtered %>% filter(in_113 == 1)
  } else if (input$session2 == "114") {
    filtered <- filtered %>% filter(in_114 == 1)
  } else if (input$session2 == "115") {
    filtered <- filtered %>% filter(in_115 == 1)
  }

  mat <- filtered %>% select(-bioguideId, -label, -party, -in_113, -in_114, -in_115)
  rownames(mat) <- filtered$label
  n <- input$matrix_page
  mat[, (50 * (n - 1) + 1):(50 * n)]
  #mat[, 1:50]
})

renderD3heatmap({
  d3heatmap(
  data_heatmap(), 
  dendrogram = "none",
  colors = viridis(10)
)
})

```

<!-- Co-sponsorship Network {data-width=300} -->
<!-- ------------------------------------ -->

<!-- ### Network  -->

<!-- ```{r, eval = FALSE} -->
<!-- edges <- reactive({ -->
<!--   simp_edges %>% -->
<!--     arrange(desc(weight)) %>% -->
<!--     filter(weight > quantile(weight, input$edge_filter)) -->
<!-- }) -->

<!-- #filter(from %in% head(nodes_subset()$bioguideId, 10) | to %in% head(nodes_subset()$bioguideId, 10)) %>% -->

<!-- renderForceNetwork({ -->
<!--   n <- nodes_subset() -->
<!--   e <- simp_edges %>% -->
<!--     filter(from %in% n$bioguideId | to %in% n$bioguideId) %>% -->
<!--     mutate(source = match(from, n$bioguideId) - 1, -->
<!--            target = match(to, n$bioguideId) - 1) -->

<!--   forceNetwork(Links = e, Nodes = n, -->
<!--              Source = "source", Target = "target", -->
<!--              Value = "weight", NodeID = "label", Group = "party", -->

<!--              # -- Nodes and labels -->
<!--              fontSize = 15, -->
<!--              fontFamily = "sans-serif", -->
<!--              opacity = 0.6, -->
<!--              opacityNoHover = 0.5, -->

<!--              # -- Edges -->
<!--              arrows = TRUE, -->
<!--              linkColour = c("grey", "grey"), -->

<!--              # -- Layout -->
<!--              linkDistance = 100, -->
<!--              charge = -30, -->

<!--              # -- General params -->
<!--              colourScale = JS('d3.scaleOrdinal().range(["green", "blue", "red"]).domain(function(d) { (d.party); });'), -->
<!--              zoom = TRUE, -->
<!--              bounded = TRUE -->
<!--              ) -->
<!-- }) -->
<!-- ``` -->

<!-- ### Other -->
